
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dayinta-PC
 */
public class Volume extends javax.swing.JFrame {

    /**
     * Creates new form Volume
     */
    public Volume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PBalok = new javax.swing.JTextField();
        LBalok = new javax.swing.JTextField();
        TBalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        VKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JBola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        VBola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Program Penghitungan Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 330, 30);

        jTabbedPane1.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel2.setText("Masukan Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 120, 30);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel3.setText("Masukan Lebar     :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 70, 120, 30);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel4.setText("Masukan Tinggi    :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 110, 120, 30);
        jPanel1.add(PBalok);
        PBalok.setBounds(200, 30, 130, 30);

        LBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBalokActionPerformed(evt);
            }
        });
        jPanel1.add(LBalok);
        LBalok.setBounds(200, 70, 130, 30);

        TBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBalokActionPerformed(evt);
            }
        });
        jPanel1.add(TBalok);
        TBalok.setBounds(200, 110, 130, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 70, 30, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 110, 30, 30);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 30, 30, 30);

        VBalok.setText("Volume");
        VBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBalokActionPerformed(evt);
            }
        });
        jPanel1.add(VBalok);
        VBalok.setBounds(200, 150, 80, 40);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel8.setText("Masukan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(140, 20, 150, 30);
        jPanel2.add(SKubus);
        SKubus.setBounds(140, 50, 100, 40);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 60, 30, 30);

        VKubus.setText("Volume");
        VKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VKubusActionPerformed(evt);
            }
        });
        jPanel2.add(VKubus);
        VKubus.setBounds(140, 100, 100, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel10.setText("Masukan Panjang Jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(140, 20, 170, 15);

        JBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBolaActionPerformed(evt);
            }
        });
        jPanel3.add(JBola);
        JBola.setBounds(140, 50, 110, 40);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(250, 50, 20, 40);

        VBola.setText("Volume");
        VBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBolaActionPerformed(evt);
            }
        });
        jPanel3.add(VBola);
        VBola.setBounds(150, 110, 90, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 440, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LBalokActionPerformed

    private void TBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBalokActionPerformed

    private void VBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(PBalok.getText());
        lebar = Integer.parseInt(LBalok.getText());
        tinggi = Integer.parseInt(TBalok.getText());
        int hasil= panjang*lebar*tinggi;

        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"ERROR:"+e,"GAGAL",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VBalokActionPerformed

    private void VKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(SKubus.getText());
        int hasil =sisi*sisi*sisi;

        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah : "+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"ERROR:"+e,"GAGAL",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VKubusActionPerformed

    private void JBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBolaActionPerformed

    private void VBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBolaActionPerformed
        // TODO add your handling code here:
        int jari;
        jari= Integer.parseInt(JBola.getText());
        float hasil =(float) (4*Math.PI*jari*jari*jari/3);

        try{
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah : "+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"ERROR:"+e,"GAGAL",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JBola;
    private javax.swing.JTextField LBalok;
    private javax.swing.JTextField PBalok;
    private javax.swing.JTextField SKubus;
    private javax.swing.JTextField TBalok;
    private javax.swing.JButton VBalok;
    private javax.swing.JButton VBola;
    private javax.swing.JButton VKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
